# VARIABLES
@baseUrl = http://localhost:3000/api
@token = {{authUser.response.body.token}}

###
# @name heathCheck
GET {{baseUrl}}

### USERS
# @name createUser
POST {{baseUrl}}/user
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "username": "admin",
    "password": "senha123",
    "email": "admin@admin.com",
    "role": "admin"
}
###
# @name registerUser
POST {{baseUrl}}/register
Content-Type: application/json

{
    "username": "admin",
    "password": "senha123",
    "email": "admin@admin.com",
    "role": "admin"
}
###
# @name authUser
POST {{baseUrl}}/login
Content-Type: application/json

{
    "email": "admin@admin.com",
    "password": "senha123"
}
### 
# @name getUsers
GET {{baseUrl}}/user?page=0&page_size=10




### SCHEDULES
# @name createSchedule
POST {{baseUrl}}/schedule
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "studentId": "21aa9b7e-0424-4622-8f3f-51ce677128e1",
    "trainingsIds": ["ae3957cf-4c03-408b-9fea-7014b5ad3d7c"],
    "startDate": "2025-07-18",
    "finishDate": "2025-07-19"
}



### EXERCISES
# @name createExercise
POST {{baseUrl}}/exercise
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "exercicio legal 2",
    "equipment": "n sei"
}
### 
# @name getExercises
GET {{baseUrl}}/exercise?page=0&page_size=10
Authorization: Bearer {{token}}




### TRAININGS
# @name createTraining
POST {{baseUrl}}/training
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "treino legal",
    "dayOfWeek": "monday",
    "exercisesIds": []
}
### 
# @name getTrainings
GET {{baseUrl}}/training?page=0&page_size=10&include_exercises=1
Authorization: Bearer {{token}}

