# VARIABLES
@baseUrl = http://localhost:3000/api
@token = {{authUser.response.body.token}}

###
# @name heathCheck
GET {{baseUrl}}

### USERS
# @name createUser
POST {{baseUrl}}/user
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "username": "admin",
    "password": "senha123",
    "email": "admin@admin.com",
    "role": "admin"
}
###
# @name registerUser
POST {{baseUrl}}/register
Content-Type: application/json

{
    "username": "admin",
    "password": "senha123",
    "email": "admin@admin.com",
    "role": "admin"
}
###
# @name authUser
POST {{baseUrl}}/login
Content-Type: application/json

{
    "email": "admin@admin.com",
    "password": "senha123"
}
### 
# @name getUsers
GET {{baseUrl}}/user?page=0&page_size=10
Authorization: Bearer {{token}}




### EXERCISES
# @name createExercise
POST {{baseUrl}}/exercise
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "exercicio legal 2",
    "equipment": "n sei"
}
### 
# @name getExercises
GET {{baseUrl}}/exercise?page=0&page_size=10
Authorization: Bearer {{token}}




### TRAININGS
# @name createTraining
POST {{baseUrl}}/training
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "treino legal",
    "dayOfWeek": "monday",
    "exercisesIds": []
}
### 
# @name getTrainings
GET {{baseUrl}}/training?page=0&page_size=10&include_exercises=1
Authorization: Bearer {{token}}

