services:
  gym:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: gym
    ports:
      - 5432:5432
    volumes:
      - ./docker:/var/lib/postgresql/data
